### ISSUE TITLE
Issues registering schema via gradle 8.2.1

### ISSUE THREAD

**Issue by nikhil-nomula** [ImFlog/schema-registry-plugin#163]
My gradle file looks like this 

```
buildscript {
    dependencies {
        classpath "org.apache.avro:avro:1.11.3"
        classpath "com.github.imflog:kafka-schema-registry-gradle-plugin:X.X.X-SNAPSHOT"
    }
}

plugins {
    id 'java'
    id 'java-library'
    id 'idea'
    id "com.github.imflog.kafka-schema-registry-gradle-plugin" version "1.12.0"
}

repositories {
    maven { url 'https://artifactory.tools.finishline.com/artifactory/libs-release' }
}

dependencies {
    implementation group: 'org.apache.avro', name: 'avro', version: '1.11.3'
}

schemaRegistry {
    url = '${registry_url}'
    credentials {
        username = "${registry_username}"
        password = "${registry_password}"
    }
    register {
        subject('testSubject', 'src/main/avro/testavro.avsc', 'AVRO')
    }
}
```

However when I run the registerSchemasTask I get 

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Is it mandatory to have ssl config if not is there a way to skip that?

**Comment by ImFlog** [comment]
Hello,

Based on your error message, I think the issue is that the SSL certificate used by your schema registry is not recognized automatically by your JVM. I am not an expert on those kind of issue but I think that is because the cert is not public ?

If so, you need to configure the keystore certificate using the [ssl extension](https://github.com/ImFlog/schema-registry-plugin/blob/6a4ed337c06583ce88ee4d0e33fcb443b570454e/src/integration/kotlin/com/github/imflog/schema/registry/security/SslIT.kt#L95).

**Comment by ImFlog** [comment]
I found this parameter in the Confluent documentation : https://docs.confluent.io/platform/current/schema-registry/installation/config.html#kafkastore-ssl-endpoint-identification-algorithm
Is it what you are trying to do ? Bypass the ssl validation ?

I can understand that for certain non-production cases, you would want to do that. I guess I could throw a PR that allow an arbitrary `Map<String, Any>` to configure the client instead of restraining to ssl configuration only.

That would still be compatible with what we have currently while allowing further configuration.

Does this make any sense for your issue ? 
I think I will do as I said if so.

**Comment by ImFlog** [comment]
I will merge this issue with the #165 => Passing a Map<String, Any> to configure the client.
