### ISSUE TITLE
Old versions of schema are being deleted

### ISSUE THREAD

**Issue by darrenhaken** [ImFlog/schema-registry-plugin#26]
I have seen a strange behaviour whereby old versions of our schema have vanished from the schema registry.

How does this plugin increment the version? Is there a way it might have overwritten old versions?

**Comment by ImFlog** [comment]
Hello thank you for using the plugin :)
The plugin has no mechanism for deleting stored schemas. The versions are increment automatically by the schema registry when you register one under the same subject.

My guess on your issue is that the retention set on your topic has passed and so your schemas have been deleted (the schema registry uses Kafka as a storing mechanism). You probably want to put an infinite retention on it.
See https://docs.confluent.io/current/schema-registry/index.html for more background around how your schemas are stored.

Tell me if it helps you.

**Comment by darrenhaken** [comment]
@ImFlog thanks for the answer, I think you've nailed it!

**Comment by ImFlog** [comment]
I'm closing this then ;)
