### ISSUE TITLE
Protobuf support

### ISSUE THREAD

**Issue by gustavomonarin** [ImFlog/schema-registry-plugin#39]
Any plans to support protobuf and json schema (from confluent platform 5.5+)?

**Comment by ImFlog** [comment]
Hello,
I learned about this new feature yesterday and tried the version upgrade as is. But it failed because of a missing dependency.
First step will be to fix it so people can still use the plugin for Avro schema, then I will think about how to add the other schema types.
Will probably start next week.
Thanks for the interest 😉

**Comment by gustavomonarin** [comment]
Awesome, thank you for so fast reply. 

I had checkout the plugin code and saw that the project is using org.apache.avro.Schema directly for the parsing. In the maven plugin they use the idea of [providers](https://github.com/confluentinc/schema-registry/commit/1b19d5e35b9bb6272ddad1f95a5effe479de3a9b#diff-4b8d0ed6216ecaefec578d01c4d8c4b4R87) which could make the code more flexible. 

Please let me know if I can help somehow ;)
